# Generated by Django 6.0.7 on 2026-07-31 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='companis',
            new_name='company',
        ),
    ]
